name: screen_state
description: A plugin for reporting screen events while the flutter application is running in background. Works for Android and iOS only.
version: 4.0.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/screen_state

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.screen_state
        pluginClass: ScreenStatePlugin
      ios:
        pluginClass: ScreenStatePlugin
