name: movisens_flutter
description: A Flutter plugin for Movisens devices, which connects to the device and listens for incoming data.
version: 3.1.2
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/movisens_flutter

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.6.0"
  
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  flutter_blue_plus: ^1.29.1
  rxdart: ^0.27.6
  logging: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
