name: mobility_features_example
description: An example app for the Mobility Features package.
publish_to: "none" 

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  carp_background_location: ^4.0.0

  mobility_features:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
